version: '3'
services:
  db:
    build: .
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 3306:3306
    volumes:
      - ./src_local:/src_container
